name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile

      - run: yarn run build

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        mongodb-version: ["4.4"]
        mongodb-lib: ["^4.3.1"]

    env:
      NODE: ${{ matrix.node-version }}
      MONGO: ${{ matrix.mongodb-version }}

    services:
      mongodb:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile

      # peerDeps installs
      - run: yarn add -D mongodb@${{matrix.mongodb-lib}}

      - run: yarn test
        env:
          CI: true
          MONGO_DB_NAME: mongodb-queue

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: npm install --include dev

      - name: Lint
        run: npm run lint
